### ISSUE TITLE
Is the NSE data available in real time for free?

### ISSUE THREAD

**Issue by thisisashukla** [omshinde/ansesai#1]
Hi Rajat,
This is a worthy project. I have a question though. The data which is being displayed on the page is free? real-time? Or is it a mock data?

**Comment by omshinde** [comment]
Hi @thisisashukla 
Apologies for the delayed response and thanks for your kind words.
I am not sure about the frequency of the data updation. I can point to the following reference which was used for getting the NSE data - 

- https://nsetools.readthedocs.io/en/latest/index.html
The [license](https://github.com/vsjha18/nsetools/blob/master/LICENSE) is MIT license so I guess it is fine to use it.

**Comment by thisisashukla** [comment]
No need for apology buddy. thanks for your response. Keep up the good work :)
